
-- Do not edit, this file was generated by github.com/apex/rpc.

-- TYPES

{-| Item is a to-do item. -}
type alias Item =
  { createdAt : String
  , id : Int
  , text : String
  }

-- METHOD PARAMS

{-| AddItemInput params. -}
type alias AddItemInput =
  { item : String
  }

{-| GetItemsOutput params. -}
type alias GetItemsOutput =
  { items : List Item
  }

{-| RemoveItemInput params. -}
type alias RemoveItemInput =
  { id : Int
  }

{-| RemoveItemOutput params. -}
type alias RemoveItemOutput =
  { item : Item
  }

-- METHODS

addItem : AddItemInput 
addItem = 
   ...

getItems : GetItemsInput 
getItems = 
   ...

removeItem : RemoveItemInput 
removeItem = 
   ...

-- DECODERS

itemDecoder : Decoder Item
itemDecoder =
    Decode.success Item
      |> required "created_at" string
      |> required "id" int
      |> required "text" string


addItemInputDecoder : Decoder AddItemInput
addItemInputDecoder =
    Decode.success AddItemInput
      |> required "item" string


getItemsOutputDecoder : Decoder GetItemsOutput
getItemsOutputDecoder =
    Decode.success GetItemsOutput
      |> required "items" (list itemDecoder)


removeItemInputDecoder : Decoder RemoveItemInput
removeItemInputDecoder =
    Decode.success RemoveItemInput
      |> required "id" int


removeItemOutputDecoder : Decoder RemoveItemOutput
removeItemOutputDecoder =
    Decode.success RemoveItemOutput
      |> required "item" itemDecoder


